### ISSUE TITLE
Upgrade to be compatible with newer Intellij versions

### ISSUE THREAD

**Issue by hschenke** [JetBrains-Research/anti-copy-paster#20]
currently not useable with IntelliJ IDEA 2022.1

**Comment by raipc** [comment]
The reason: tensorflow cannot load `tensorflow_framework.1.dylib` because `NativeLibrary.class.getPackage()` returns null (probably because of changes in classloader implementation), so versioned library name evaluates to `tensorflow_framework.dylib` which is not found in the class path.
As a workaround, `tensorflow_framework.{1.dylib,so.1)` can be loaded by the ACP.
See `org.tensorflow.NativeLibrary` in `libtensorflow`

**Comment by raipc** [comment]
Also, model should be extracted to TMPDIR or directory where IDEA plugins store their data (I'm not familiar with plugins development) instead of WORKDIR. Seems like in latest IDEA WORKDIR is set to `/` on MacOS

**Comment by hschenke** [comment]
Please merge someone :)
